version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=admin 
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: pg_isready -U admin -d test
      interval: 5s
      timeout: 5s
      retries: 5